[package]
name = "i-read"
version = "0.0.6"
authors = ["s2terminal <suzuki.sh@s2terminal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"
regex = "1"
dialoguer = "0.6.2"
pulldown-cmark = "0.7.2"
ctrlc = "3.1.6"
console = "0.11.3"
