name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup musl
      run: rustup target add x86_64-unknown-linux-musl
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: i-read-linux-amd64
        path: target/x86_64-unknown-linux-musl/release/i-read

    - name: Compress
      run: |
        mv target/x86_64-unknown-linux-musl/release/i-read iread
        tar --gunzip --create --file iread.tar.gz iread

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: iread.tar.gz
        asset_name: iread.tar.gz
        asset_content_type: application/octet-stream
